### ISSUE TITLE
Unlike epr, using --help flag doesn't show the long help on epy.

### ISSUE THREAD

**Issue by PrajwalX7** [wustho/epy#11]
![Screenshot_2020-10-03_20-06-17](https://user-images.githubusercontent.com/49450563/94994308-6e6fb980-05b4-11eb-8b9f-41abfe6c1aa4.png)
**epr** on the left & **epy** on the right.

**Comment by wustho** [comment]
Yes, indeed. The difference is that in `epr` keybinds help is served statically (I wrote the keybindings manually). While in `epy` is generated dynamically and you can access them in app via key "?" but not via "--help" in shell.

This happens because in `epy` you can customize keybindings by editing `~/.config/epy/config.json` while you cannot do so in `epr`.
