### ISSUE TITLE
External dictionary integration.

### ISSUE THREAD

**Issue by avisihag** [wustho/epy#16]
The help menu doesn't say anything about the dictionary integration. Please put some light on how to do it.

**Comment by wustho** [comment]
Yes, sorry about that. Since it is very simple integration. I will try to add it to Readme next time. So all you have to do is install one of command line dictionary clients. Like: sdcv or dict (see: https://askubuntu.com/questions/191125/is-there-an-offline-command-line-dictionary).

After that you will be able to find definition of word by pressing `d`, and prompt will appear to let you type in word to define.

**Comment by Daniyal-Ahmed922** [comment]
Error: wkdict                                                                            
  -------------  


im getting this Error on windows (Python 3.10) when i use `d` to check meaning of a word
