### ISSUE TITLE
PageScrollAnimation seems to be always True

### ISSUE THREAD

**Issue by 097115** [wustho/epy#28]
Tried to set `PageScrollAnimation` to `False` [here](https://github.com/wustho/epy/blob/b43ef4c87f654c8d3fed6d949be4ea784006145f/epy.py#L61) but it seems something still sets it to `True` somewhere down the road :) (i.e., I can't turn it off)

This is happening on b43ef4c.

**Comment by wustho** [comment]
Hello there, thanks for giving detailed traceback of the issue...

Can you try setting `PageScrollAnimation` to `true` in the config file instead of the code directly? Does it work?

Config file located in:

- Linux: `~/.config/epy/config.json` or `~/.epy/config.json`
- Windows: `%USERPROFILE%\.epy\config.json`

**Comment by 097115** [comment]
@wustho 

Oh, sorry, mate, I completely missed that there's a config file :)

Everything works as intended, sorry for the mess! 

(And thanks for this superb reader :)
